name = "inspect-key-server"
main = "worker.js"
compatibility_date = "2024-11-10"

[vars]
KEYS_URL = "https://raw.githubusercontent.com/Liexxxx/inspect-key-server/main/keys.json"

[kv_namespaces]
binding = "KV"
id = "dab50c7443164864bebe4de8f1902d14"

[[durable_objects]]
binding = "LICENSE_DO"
class_name = "LicenseObject"

[[migrations]]
tag = "v1"
new_classes = ["LicenseObject"]
